// Compatibility API. New consumers should import named helpers from focused modules.
import { downloadCsv, jsonToCsv, parseCsv } from './csv';
import { getCronString, getNextExecutionTime, parseCronExpression } from './cron';
import { formatDate, formatDateTime, formatDateTimeValue, parseDateTimeValue, formatUtcDate, getCurrentTime, getDate, getDateAndTime, getDateAndTimeShort, getDateTimeWithOrdinalSuffix, getDateWithOrdinalSuffix, getRelativeTime, getTime, handleDateTimeInput } from './date';
import { getFeature, getFeatures, getIdentificationId, getProductIdentificationValue } from './product';
import { isAppEmbedded, isMoqui, copyToClipboard, dedupeFacilities, formatCurrency, formatPhoneNumber, generateInternalId, getColorByDesc, getFacilityChipLabel, getMaargBaseURL, getMaargURL, getOMSInstanceName, getOmsURL, getStatusColor, getTelecomCountryCode, getToken, getTokenExpiration, goToOms, hasActiveFilters, hasError, hasWebcamAccess, isError, isPdf, isValidCarrierCode, isValidDeliveryDays, isValidEmail, isValidPassword, isValidVersion, isVersionGreaterOrEqual, jsonParse, parseBooleanSetting, showToast, sortSequence } from './core';
export type { JsonToCsvOption } from './csv';

export const commonUtil = {
  isAppEmbedded,
  isMoqui,
  copyToClipboard,
  dedupeFacilities,
  downloadCsv,
  formatCurrency,
  formatDate,
  formatDateTime,
  formatDateTimeValue,
  parseDateTimeValue,
  formatPhoneNumber,
  formatUtcDate,
  generateInternalId,
  getColorByDesc,
  getCurrentTime,
  getCronString,
  getDate,
  getDateAndTime,
  getDateAndTimeShort,
  getDateTimeWithOrdinalSuffix,
  getDateWithOrdinalSuffix,
  getFacilityChipLabel,
  getFeature,
  getFeatures,
  getIdentificationId,
  getMaargBaseURL,
  getMaargURL,
  getNextExecutionTime,
  getOMSInstanceName,
  getOmsURL,
  getProductIdentificationValue,
  getRelativeTime,
  getStatusColor,
  getTelecomCountryCode,
  getTime,
  getToken,
  getTokenExpiration,
  goToOms,
  handleDateTimeInput,
  hasActiveFilters,
  hasError,
  hasWebcamAccess,
  isError,
  isPdf,
  isValidCarrierCode,
  isValidDeliveryDays,
  isValidEmail,
  isValidPassword,
  isValidVersion,
  isVersionGreaterOrEqual,
  jsonParse,
  jsonToCsv,
  parseBooleanSetting,
  parseCronExpression,
  parseCsv,
  showToast,
  sortSequence
}
